spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    platform: h2
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
welcome:
  message: Hello Sandeep Suvarna!
server:
  port: '8082'