#name should match the config server property file limits-services.properties
spring.application.name=limits-services
spring.config.import=optional:configserver:http://localhost:8888

#to pick profile from config server
spring.profiles.active=dev
spring.cloud.config.profile=dev

limits-services.minimum=20
limits-services.maximum=5000

server.port=8080

